routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/home');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home')->middleware('auth');


Route::resource('expenses', 'ExpensesController')->middleware('auth');
Route::get('/changepassword', 'HomeController@change')->middleware('auth');
Route::post('/changepassword', 'HomeController@changePassword')->middleware('auth');


Route::group(['middleware' => 'App\Http\Middleware\AdminMiddleware'], function()
{
    Route::resource('users', 'UsersController');
    Route::resource('roles', 'RolesController');
    Route::resource('categories', 'ExpenseCategoriesController');
});

app/Http/Controllers/ExpenseCategoriesController.php
<?php

namespace App\Http\Controllers;

use App\ExpenseCategories;
use Illuminate\Http\Request;

class ExpenseCategoriesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = ExpenseCategories::paginate(10);
        return view('expense_categories.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required',
            'description' => 'required'
        ]);
        
        ExpenseCategories::create($request->all());

        return back();
        
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\ExpenseCategories  $expenseCategories
     * @return \Illuminate\Http\Response
     */
    public function show(ExpenseCategories $expenseCategories)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\ExpenseCategories  $expenseCategories
     * @return \Illuminate\Http\Response
     */
    public function edit(ExpenseCategories $expenseCategories)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\ExpenseCategories  $expenseCategories
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'required',
            'description' => 'required'
        ]);
        ExpenseCategories::find($id)->update($request->all());
        return back();    
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\ExpenseCategories  $expenseCategories
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        ExpenseCategories::find($id)->delete();

        return response()->json(1);
    }
}

resources/views/expense_categories/modal/categorymodal.blade.php
<form action="{{ route('categories.store') }}" method="POST" id="categoryForm">
@csrf 
    <input type="hidden" name="_method" id="method">
    <div class="modal fade" id="categorymodal" tabindex="-1" role="dialog" aria-labelledby="modelTitleId" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="modalTitle"></h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                </div>
                <div class="modal-body">
                    <table class="table" >
                        <input type="hidden" name="id" id="inputId" />
                        <tr >
                            <td class="border-none">
                                <label for="name">Display Name:</label>
                            </td>
                            <td class="border-none">
                                <input type="text" id="inputName" name="name" class="form-control rounded-0 border border-dark"/>
                            </td>
                        </tr>
                        <tr>
                            <td class="border-none">
                                <label for="description">Description:</label>
                            </td>
                            <td class="border-none">
                                <input type="description" id="inputDescription" name="description" class="form-control rounded-0 border border-dark"/>
                            </td>
                        </tr>
                    </table>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger mr-auto" id="btnDelete" style="display:none;" data-token="{{ csrf_token() }}">Delete</button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" id="btnSubmit" class="btn btn-primary">Save</button>
                </div>
            </div>
        </div>
    </div>
</form>