routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/home');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home')->middleware('auth');


Route::resource('expenses', 'ExpensesController')->middleware('auth');
Route::get('/changepassword', 'HomeController@change')->middleware('auth');
Route::post('/changepassword', 'HomeController@changePassword')->middleware('auth');


Route::group(['middleware' => 'App\Http\Middleware\AdminMiddleware'], function()
{
    Route::resource('users', 'UsersController');
    Route::resource('roles', 'RolesController');
    Route::resource('categories', 'ExpenseCategoriesController');
});

app/Http/Controllers/ExpensesController.php
<?php

namespace App\Http\Controllers;

use App\Expenses;
use Illuminate\Http\Request;
use App\ExpenseCategories;

class ExpensesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $expenses = Expenses::with('category')->latest()->paginate(10);
        $categories = ExpenseCategories::all();
        return view('expenses.index', compact('expenses', 'categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'category_id' => 'required',
            'amount' => 'required',
            'entry_date' => 'date|required'
        ]);
        $category = ExpenseCategories::find($request->category_id);

        $category->expenses()->create($request->all());
        
        return back();
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Expenses  $expenses
     * @return \Illuminate\Http\Response
     */
    public function show(Expenses $expenses)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Expenses  $expenses
     * @return \Illuminate\Http\Response
     */
    public function edit(Expenses $expenses)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Expenses  $expenses
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'category_id' => 'required',
            'amount' => 'required',
            'entry_date' => 'date|required'
        ]);
        
        $expense = Expenses::find($request->id);
        $expense->amount = $request->amount;
        $expense->entry_date = $request->entry_date;
        $expense->category_id = $request->category_id;
        $expense->save();


        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Expenses  $expenses
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Expenses::find($id)->delete();
        
        return response()->json(1);
    }
}

resources/views/expenses/modal/expensemodal.blade.php
<form action="{{ route('expenses.store') }}" method="POST" id="expenseForm">
@csrf 
    <input type="hidden" name="_method" id="method">
    <div class="modal fade" id="expensemodal" tabindex="-1" role="dialog" aria-labelledby="modelTitleId" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="modalTitle"></h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                </div>
                <div class="modal-body">
                    <table class="table" >
                        <input type="hidden" name="id" id="inputId" />
                        <tr >
                            <td class="border-none">
                                <label for="category">Expense Category:</label>
                            </td>
                            <td class="border-none">
                                 <select id="inputCategory" class="form-control border border-dark rounded-0 font-weight-bold" name="category_id">
                                    <option value="">Select Category </option> 
                                    @forelse($categories as $category)
                                        <option value="{{ $category->id }}" class="text-uppercase">{{ $category->name }}</option>
                                    @empty
                                        <option>Please Create Category</option>
                                    @endforelse
                                </select>
                            </td>
                        </tr>
                        <tr>
                            <td class="border-none">
                                <label for="amount">Amount:</label>
                            </td>
                            <td class="border-none">
                                <input type="number" id="inputAmount" min="0" name="amount" class="form-control rounded-0 border border-dark"/>
                            </td>
                        </tr>
                        <tr>
                            <td class="border-none">
                                <label for="entry_date">Entry Date:</label>
                            </td>
                            <td class="border-none">
                                <input type="date" id="inputDate" name="entry_date" class="form-control rounded-0 border border-dark"/>
                            </td>
                        </tr>
                    </table>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger mr-auto" id="btnDelete" style="display:none;" data-token="{{ csrf_token() }}">Delete</button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" id="btnSubmit" class="btn btn-primary">Save</button>
                </div>
            </div>
        </div>
    </div>
</form>